from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOWS_ICON_PATH = FILES_DIR / 'icon_calculator.png'

# Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 30
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MININUM_WIDTH = 500
